// Code generated by "morestringer -lookup Lookup{} -output stringer.go Led Key:cconst FeatureKind"; DO NOT EDIT.

package wiimote

import (
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FeatureCore-1]
	_ = x[FeatureAccel-2]
	_ = x[FeatureIR-4]
	_ = x[FeatureSpeaker-8]
	_ = x[FeatureMotionPlus-16]
	_ = x[FeatureNunchuck-32]
	_ = x[FeatureClassicController-64]
	_ = x[FeatureBalanceBoard-128]
	_ = x[FeatureProController-256]
	_ = x[FeatureDrums-512]
	_ = x[FeatureGuitar-1024]
}

func LookupFeatureKind(name string) (FeatureKind, bool) {
	// fnv1a32 hash
	var h uint32 = 2166136261
	for i := 0; i < len(name); i++ {
		h ^= uint32(name[i])
		h *= 16777619
	}

	switch h {
	case 0x0219726b:
		if name == "FeatureAccel" {
			return FeatureAccel, true
		}
	case 0x33dc1bea:
		if name == "FeatureIR" {
			return FeatureIR, true
		}
	case 0x5ca129b7:
		if name == "FeatureClassicController" {
			return FeatureClassicController, true
		}
	case 0x5fa46612:
		if name == "FeatureDrums" {
			return FeatureDrums, true
		}
	case 0x71997d97:
		if name == "FeatureGuitar" {
			return FeatureGuitar, true
		}
	case 0x8a54c0fa:
		if name == "FeatureSpeaker" {
			return FeatureSpeaker, true
		}
	case 0x9018d2ae:
		if name == "FeatureNunchuck" {
			return FeatureNunchuck, true
		}
	case 0x934b54b8:
		if name == "FeatureProController" {
			return FeatureProController, true
		}
	case 0xb5758d69:
		if name == "FeatureBalanceBoard" {
			return FeatureBalanceBoard, true
		}
	case 0xbb96eb46:
		if name == "FeatureCore" {
			return FeatureCore, true
		}
	case 0xdf1c6893:
		if name == "FeatureMotionPlus" {
			return FeatureMotionPlus, true
		}
	}
	return 0, false
}

const (
	_FeatureKind_name_0 = "FeatureCoreFeatureAccel"
	_FeatureKind_name_1 = "FeatureIR"
	_FeatureKind_name_2 = "FeatureSpeaker"
	_FeatureKind_name_3 = "FeatureMotionPlus"
	_FeatureKind_name_4 = "FeatureNunchuck"
	_FeatureKind_name_5 = "FeatureClassicController"
	_FeatureKind_name_6 = "FeatureBalanceBoard"
	_FeatureKind_name_7 = "FeatureProController"
	_FeatureKind_name_8 = "FeatureDrums"
	_FeatureKind_name_9 = "FeatureGuitar"
)

var (
	_FeatureKind_index_0 = [...]uint8{0, 11, 23}
)

func (i FeatureKind) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _FeatureKind_name_0[_FeatureKind_index_0[i]:_FeatureKind_index_0[i+1]]
	case i == 4:
		return _FeatureKind_name_1
	case i == 8:
		return _FeatureKind_name_2
	case i == 16:
		return _FeatureKind_name_3
	case i == 32:
		return _FeatureKind_name_4
	case i == 64:
		return _FeatureKind_name_5
	case i == 128:
		return _FeatureKind_name_6
	case i == 256:
		return _FeatureKind_name_7
	case i == 512:
		return _FeatureKind_name_8
	case i == 1024:
		return _FeatureKind_name_9
	default:
		return "FeatureKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Led1-1]
	_ = x[Led2-2]
	_ = x[Led3-4]
	_ = x[Led4-8]
}

func LookupLed(name string) (Led, bool) {
	// fnv1a32 hash
	var h uint32 = 2166136261
	for i := 0; i < len(name); i++ {
		h ^= uint32(name[i])
		h *= 16777619
	}

	switch h {
	case 0xe07c3088:
		if name == "Led2" {
			return Led2, true
		}
	case 0xe17c321b:
		if name == "Led3" {
			return Led3, true
		}
	case 0xe37c3541:
		if name == "Led1" {
			return Led1, true
		}
	case 0xe67c39fa:
		if name == "Led4" {
			return Led4, true
		}
	}
	return 0, false
}

const (
	_Led_name_0 = "Led1Led2"
	_Led_name_1 = "Led3"
	_Led_name_2 = "Led4"
)

var (
	_Led_index_0 = [...]uint8{0, 4, 8}
)

func (i Led) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Led_name_0[_Led_index_0[i]:_Led_index_0[i+1]]
	case i == 4:
		return _Led_name_1
	case i == 8:
		return _Led_name_2
	default:
		return "Led(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyLeft-0]
	_ = x[KeyRight-1]
	_ = x[KeyUp-2]
	_ = x[KeyDown-3]
	_ = x[KeyA-4]
	_ = x[KeyB-5]
	_ = x[KeyPlus-6]
	_ = x[KeyMinus-7]
	_ = x[KeyHome-8]
	_ = x[KeyOne-9]
	_ = x[KeyTwo-10]
	_ = x[KeyX-11]
	_ = x[KeyY-12]
	_ = x[KeyTL-13]
	_ = x[KeyTR-14]
	_ = x[KeyZL-15]
	_ = x[KeyZR-16]
	_ = x[KeyThumbL-17]
	_ = x[KeyThumbR-18]
	_ = x[KeyC-19]
	_ = x[KeyZ-20]
	_ = x[KeyStrumBarUp-21]
	_ = x[KeyStrumBarDown-22]
	_ = x[KeyFretFarUp-23]
	_ = x[KeyFretUp-24]
	_ = x[KeyFretMid-25]
	_ = x[KeyFretLow-26]
	_ = x[KeyFretFarLow-27]
}

func LookupKey(name string) (Key, bool) {
	// fnv1a32 hash
	var h uint32 = 2166136261
	for i := 0; i < len(name); i++ {
		h ^= uint32(name[i])
		h *= 16777619
	}

	switch h {
	case 0x141fa38c:
		if name == "KEY_T_L" {
			return KeyTL, true
		}
	case 0x148b16af:
		if name == "KEY_FRET_FAR_LOW" {
			return KeyFretFarLow, true
		}
	case 0x15d59daa:
		if name == "KEY_Z_L" {
			return KeyZL, true
		}
	case 0x17d5a0d0:
		if name == "KEY_Z_R" {
			return KeyZR, true
		}
	case 0x2a1fc62e:
		if name == "KEY_T_R" {
			return KeyTR, true
		}
	case 0x32f79d43:
		if name == "KEY_MINUS" {
			return KeyMinus, true
		}
	case 0x4e48ce9d:
		if name == "KEY_FRET_LOW" {
			return KeyFretLow, true
		}
	case 0x6316fc03:
		if name == "KEY_ONE" {
			return KeyOne, true
		}
	case 0x6d1b1e7a:
		if name == "KEY_FRET_FAR_UP" {
			return KeyFretFarUp, true
		}
	case 0x74456408:
		if name == "KEY_STRUM_BAR_UP" {
			return KeyStrumBarUp, true
		}
	case 0x74e5bdac:
		if name == "KEY_UP" {
			return KeyUp, true
		}
	case 0x770b24ad:
		if name == "KEY_TWO" {
			return KeyTwo, true
		}
	case 0x7e64f0b4:
		if name == "KEY_FRET_UP" {
			return KeyFretUp, true
		}
	case 0x8c4aea39:
		if name == "KEY_DOWN" {
			return KeyDown, true
		}
	case 0x9bc9f129:
		if name == "KEY_PLUS" {
			return KeyPlus, true
		}
	case 0xa241d25a:
		if name == "KEY_HOME" {
			return KeyHome, true
		}
	case 0xb5cfb6e4:
		if name == "KEY_LEFT" {
			return KeyLeft, true
		}
	case 0xc3398b79:
		if name == "KEY_FRET_MID" {
			return KeyFretMid, true
		}
	case 0xdbf48f31:
		if name == "KEY_RIGHT" {
			return KeyRight, true
		}
	case 0xea4b67f8:
		if name == "KEY_A" {
			return KeyA, true
		}
	case 0xec4b6b1e:
		if name == "KEY_C" {
			return KeyC, true
		}
	case 0xed4b6cb1:
		if name == "KEY_B" {
			return KeyB, true
		}
	case 0xf1f07f9e:
		if name == "KEY_THUMB_R" {
			return KeyThumbR, true
		}
	case 0xf24b7490:
		if name == "KEY_Y" {
			return KeyY, true
		}
	case 0xf34b7623:
		if name == "KEY_X" {
			return KeyX, true
		}
	case 0xf54b7949:
		if name == "KEY_Z" {
			return KeyZ, true
		}
	case 0xf64aa53d:
		if name == "KEY_STRUM_BAR_DOWN" {
			return KeyStrumBarDown, true
		}
	case 0xfbf08f5c:
		if name == "KEY_THUMB_L" {
			return KeyThumbL, true
		}
	}
	return 0, false
}

const _Key_name = "KEY_LEFTKEY_RIGHTKEY_UPKEY_DOWNKEY_AKEY_BKEY_PLUSKEY_MINUSKEY_HOMEKEY_ONEKEY_TWOKEY_XKEY_YKEY_T_LKEY_T_RKEY_Z_LKEY_Z_RKEY_THUMB_LKEY_THUMB_RKEY_CKEY_ZKEY_STRUM_BAR_UPKEY_STRUM_BAR_DOWNKEY_FRET_FAR_UPKEY_FRET_UPKEY_FRET_MIDKEY_FRET_LOWKEY_FRET_FAR_LOW"

var _Key_index = [...]uint8{0, 8, 17, 23, 31, 36, 41, 49, 58, 66, 73, 80, 85, 90, 97, 104, 111, 118, 129, 140, 145, 150, 166, 184, 199, 210, 222, 234, 250}

func (i Key) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Key_index)-1 {
		return "Key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Key_name[_Key_index[idx]:_Key_index[idx+1]]
}
