// Code generated by "stringer -type InterfaceType,Led,Key,KeyState,MonitorType -output stringer.go"; DO NOT EDIT.

package xwiimote

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InterfaceCore-1]
	_ = x[InterfaceAccel-2]
	_ = x[InterfaceIR-4]
	_ = x[InterfaceMotionPlus-256]
	_ = x[InterfaceNunchuk-512]
	_ = x[InterfaceClassicController-1024]
	_ = x[InterfaceBalanceBoard-2048]
	_ = x[InterfaceProController-4096]
	_ = x[InterfaceDrums-8192]
	_ = x[InterfaceGuitar-16384]
	_ = x[InterfaceAll-32519]
	_ = x[InterfaceWritable-65536]
}

const _InterfaceType_name = "InterfaceCoreInterfaceAccelInterfaceIRInterfaceMotionPlusInterfaceNunchukInterfaceClassicControllerInterfaceBalanceBoardInterfaceProControllerInterfaceDrumsInterfaceGuitarInterfaceAllInterfaceWritable"

var _InterfaceType_map = map[InterfaceType]string{
	1:     _InterfaceType_name[0:13],
	2:     _InterfaceType_name[13:27],
	4:     _InterfaceType_name[27:38],
	256:   _InterfaceType_name[38:57],
	512:   _InterfaceType_name[57:73],
	1024:  _InterfaceType_name[73:99],
	2048:  _InterfaceType_name[99:120],
	4096:  _InterfaceType_name[120:142],
	8192:  _InterfaceType_name[142:156],
	16384: _InterfaceType_name[156:171],
	32519: _InterfaceType_name[171:183],
	65536: _InterfaceType_name[183:200],
}

func (i InterfaceType) String() string {
	if str, ok := _InterfaceType_map[i]; ok {
		return str
	}
	return "InterfaceType(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Led1-1]
	_ = x[Led2-2]
	_ = x[Led3-3]
	_ = x[Led4-4]
}

const _Led_name = "Led1Led2Led3Led4"

var _Led_index = [...]uint8{0, 4, 8, 12, 16}

func (i Led) String() string {
	i -= 1
	if i >= Led(len(_Led_index)-1) {
		return "Led(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Led_name[_Led_index[i]:_Led_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyLeft-0]
	_ = x[KeyRight-1]
	_ = x[KeyUp-2]
	_ = x[KeyDown-3]
	_ = x[KeyA-4]
	_ = x[KeyB-5]
	_ = x[KeyPlus-6]
	_ = x[KeyMinus-7]
	_ = x[KeyHome-8]
	_ = x[KeyOne-9]
	_ = x[KeyTwo-10]
	_ = x[KeyX-11]
	_ = x[KeyY-12]
	_ = x[KeyTL-13]
	_ = x[KeyTR-14]
	_ = x[KeyZL-15]
	_ = x[KeyZR-16]
	_ = x[KeyThumbL-17]
	_ = x[KeyThumbR-18]
	_ = x[KeyC-19]
	_ = x[KeyZ-20]
	_ = x[KeyStrumBarUp-21]
	_ = x[KeyStrumBarDown-22]
	_ = x[KeyFretFarUp-23]
	_ = x[KeyFretUp-24]
	_ = x[KeyFretMid-25]
	_ = x[KeyFretLow-26]
	_ = x[KeyFretFarLow-27]
}

const _Key_name = "KeyLeftKeyRightKeyUpKeyDownKeyAKeyBKeyPlusKeyMinusKeyHomeKeyOneKeyTwoKeyXKeyYKeyTLKeyTRKeyZLKeyZRKeyThumbLKeyThumbRKeyCKeyZKeyStrumBarUpKeyStrumBarDownKeyFretFarUpKeyFretUpKeyFretMidKeyFretLowKeyFretFarLow"

var _Key_index = [...]uint8{0, 7, 15, 20, 27, 31, 35, 42, 50, 57, 63, 69, 73, 77, 82, 87, 92, 97, 106, 115, 119, 123, 136, 151, 163, 172, 182, 192, 205}

func (i Key) String() string {
	if i >= Key(len(_Key_index)-1) {
		return "Key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Key_name[_Key_index[i]:_Key_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateReleased-0]
	_ = x[StatePressed-1]
	_ = x[StateRepeated-2]
}

const _KeyState_name = "StateReleasedStatePressedStateRepeated"

var _KeyState_index = [...]uint8{0, 13, 25, 38}

func (i KeyState) String() string {
	if i >= KeyState(len(_KeyState_index)-1) {
		return "KeyState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyState_name[_KeyState_index[i]:_KeyState_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MonitorKernel-1]
	_ = x[MonitorUdev-0]
}

const _MonitorType_name = "MonitorUdevMonitorKernel"

var _MonitorType_index = [...]uint8{0, 11, 24}

func (i MonitorType) String() string {
	if i >= MonitorType(len(_MonitorType_index)-1) {
		return "MonitorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MonitorType_name[_MonitorType_index[i]:_MonitorType_index[i+1]]
}
