// Code generated by "stringer -type InterfaceType,Led,Key,KeyState,MonitorType -output stringer.go"; DO NOT EDIT.

package xwiimote

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InterfaceCore-1]
	_ = x[InterfaceAccel-2]
	_ = x[InterfaceIR-4]
	_ = x[InterfaceMotionPlus-256]
	_ = x[InterfaceNunchuk-512]
	_ = x[InterfaceClassicController-1024]
	_ = x[InterfaceBalanceBoard-2048]
	_ = x[InterfaceProController-4096]
	_ = x[InterfaceDrums-8192]
	_ = x[InterfaceGuitar-16384]
	_ = x[InterfaceAll-32519]
}

const (
	_InterfaceType_name_0 = "InterfaceCoreInterfaceAccel"
	_InterfaceType_name_1 = "InterfaceIR"
	_InterfaceType_name_2 = "InterfaceMotionPlus"
	_InterfaceType_name_3 = "InterfaceNunchuk"
	_InterfaceType_name_4 = "InterfaceClassicController"
	_InterfaceType_name_5 = "InterfaceBalanceBoard"
	_InterfaceType_name_6 = "InterfaceProController"
	_InterfaceType_name_7 = "InterfaceDrums"
	_InterfaceType_name_8 = "InterfaceGuitar"
	_InterfaceType_name_9 = "InterfaceAll"
)

var (
	_InterfaceType_index_0 = [...]uint8{0, 13, 27}
)

func (i InterfaceType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _InterfaceType_name_0[_InterfaceType_index_0[i]:_InterfaceType_index_0[i+1]]
	case i == 4:
		return _InterfaceType_name_1
	case i == 256:
		return _InterfaceType_name_2
	case i == 512:
		return _InterfaceType_name_3
	case i == 1024:
		return _InterfaceType_name_4
	case i == 2048:
		return _InterfaceType_name_5
	case i == 4096:
		return _InterfaceType_name_6
	case i == 8192:
		return _InterfaceType_name_7
	case i == 16384:
		return _InterfaceType_name_8
	case i == 32519:
		return _InterfaceType_name_9
	default:
		return "InterfaceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Led1-1]
	_ = x[Led2-2]
	_ = x[Led3-4]
	_ = x[Led4-8]
}

const (
	_Led_name_0 = "Led1Led2"
	_Led_name_1 = "Led3"
	_Led_name_2 = "Led4"
)

var (
	_Led_index_0 = [...]uint8{0, 4, 8}
)

func (i Led) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Led_name_0[_Led_index_0[i]:_Led_index_0[i+1]]
	case i == 4:
		return _Led_name_1
	case i == 8:
		return _Led_name_2
	default:
		return "Led(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyLeft-0]
	_ = x[KeyRight-1]
	_ = x[KeyUp-2]
	_ = x[KeyDown-3]
	_ = x[KeyA-4]
	_ = x[KeyB-5]
	_ = x[KeyPlus-6]
	_ = x[KeyMinus-7]
	_ = x[KeyHome-8]
	_ = x[KeyOne-9]
	_ = x[KeyTwo-10]
	_ = x[KeyX-11]
	_ = x[KeyY-12]
	_ = x[KeyTL-13]
	_ = x[KeyTR-14]
	_ = x[KeyZL-15]
	_ = x[KeyZR-16]
	_ = x[KeyThumbL-17]
	_ = x[KeyThumbR-18]
	_ = x[KeyC-19]
	_ = x[KeyZ-20]
	_ = x[KeyStrumBarUp-21]
	_ = x[KeyStrumBarDown-22]
	_ = x[KeyFretFarUp-23]
	_ = x[KeyFretUp-24]
	_ = x[KeyFretMid-25]
	_ = x[KeyFretLow-26]
	_ = x[KeyFretFarLow-27]
}

const _Key_name = "KeyLeftKeyRightKeyUpKeyDownKeyAKeyBKeyPlusKeyMinusKeyHomeKeyOneKeyTwoKeyXKeyYKeyTLKeyTRKeyZLKeyZRKeyThumbLKeyThumbRKeyCKeyZKeyStrumBarUpKeyStrumBarDownKeyFretFarUpKeyFretUpKeyFretMidKeyFretLowKeyFretFarLow"

var _Key_index = [...]uint8{0, 7, 15, 20, 27, 31, 35, 42, 50, 57, 63, 69, 73, 77, 82, 87, 92, 97, 106, 115, 119, 123, 136, 151, 163, 172, 182, 192, 205}

func (i Key) String() string {
	if i >= Key(len(_Key_index)-1) {
		return "Key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Key_name[_Key_index[i]:_Key_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateReleased-0]
	_ = x[StatePressed-1]
	_ = x[StateRepeated-2]
}

const _KeyState_name = "StateReleasedStatePressedStateRepeated"

var _KeyState_index = [...]uint8{0, 13, 25, 38}

func (i KeyState) String() string {
	if i >= KeyState(len(_KeyState_index)-1) {
		return "KeyState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyState_name[_KeyState_index[i]:_KeyState_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MonitorKernel-1]
	_ = x[MonitorUdev-0]
}

const _MonitorType_name = "MonitorUdevMonitorKernel"

var _MonitorType_index = [...]uint8{0, 11, 24}

func (i MonitorType) String() string {
	if i >= MonitorType(len(_MonitorType_index)-1) {
		return "MonitorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MonitorType_name[_MonitorType_index[i]:_MonitorType_index[i+1]]
}
