// Code generated by "morestringer -output stringer.go Health"; DO NOT EDIT.

package irpointer

import (
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IRDead-0]
	_ = x[IRLost-1]
	_ = x[IRSingle-2]
	_ = x[IRGood-3]
}

const _Health_name = "IRDeadIRLostIRSingleIRGood"

var _Health_index = [...]uint8{0, 6, 12, 20, 26}

func (i Health) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Health_index)-1 {
		return "Health(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Health_name[_Health_index[idx]:_Health_index[idx+1]]
}
