// Code generated by "stringer -type IRHealth -output stringer.go"; DO NOT EDIT.

package irpointer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IRDead-0]
	_ = x[IRLost-1]
	_ = x[IRSingle-2]
	_ = x[IRGood-3]
}

const _IRHealth_name = "IRDeadIRLostIRSingleIRGood"

var _IRHealth_index = [...]uint8{0, 6, 12, 20, 26}

func (i IRHealth) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_IRHealth_index)-1 {
		return "IRHealth(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IRHealth_name[_IRHealth_index[idx]:_IRHealth_index[idx+1]]
}
