// Generated by gowls using arguments "-p proto -P wl_,zwlr_ -S _v1 proto/wlr-virtual-pointer-unstable-v1.xml". DO NOT EDIT.
// https://github.com/friedelschoen/wayland/cmd/gowls
//
// XML file : proto/wlr-virtual-pointer-unstable-v1.xml
//
// wlr_virtual_pointer_unstable_v1 Protocol Copyright:
//
// Copyright © 2019 Josef Gajdusek
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

// Package proto contains wayland-protocol wlr_virtual_pointer_unstable_v1
package proto

import wayland "github.com/friedelschoen/wayland"
import "fmt"

// VirtualPointer : virtual pointer
//
// This protocol allows clients to emulate a physical pointer device. The
// requests are mostly mirror opposites of those specified in wl_pointer.
type VirtualPointer struct {
	wayland.BaseProxy
	adjacent []wayland.Proxy
}

// NewVirtualPointer : virtual pointer
//
// This protocol allows clients to emulate a physical pointer device. The
// requests are mostly mirror opposites of those specified in wl_pointer.
func NewVirtualPointer() *VirtualPointer {
	return &VirtualPointer{}
}
func (i *VirtualPointer) Name() string {
	return "zwlr_virtual_pointer_v1"
}

// Motion : pointer relative motion event
//
// The pointer has moved by a relative amount to the previous request.
//
// Values are in the global compositor space.
//
// time : timestamp with millisecond granularity
// dx : displacement on the x-axis
// dy : displacement on the y-axis
func (i *VirtualPointer) Motion(time uint32, dx float64, dy float64) {
	if i == nil || !i.Valid() {
		return
	}
	w := wayland.NewMessageWriter(i, 0)
	w.WriteUint(uint32(time))
	w.WriteFixed(dx)
	w.WriteFixed(dy)
	if err := w.Finish(); err != nil {
		panic(err)
	}
}

// MotionAbsolute : pointer absolute motion event
//
// The pointer has moved in an absolute coordinate frame.
//
// Value of x can range from 0 to x_extent, value of y can range from 0
// to y_extent.
//
// time : timestamp with millisecond granularity
// x : position on the x-axis
// y : position on the y-axis
// xExtent : extent of the x-axis
// yExtent : extent of the y-axis
func (i *VirtualPointer) MotionAbsolute(time uint32, x uint32, y uint32, xExtent uint32, yExtent uint32) {
	if i == nil || !i.Valid() {
		return
	}
	w := wayland.NewMessageWriter(i, 1)
	w.WriteUint(uint32(time))
	w.WriteUint(uint32(x))
	w.WriteUint(uint32(y))
	w.WriteUint(uint32(xExtent))
	w.WriteUint(uint32(yExtent))
	if err := w.Finish(); err != nil {
		panic(err)
	}
}

// Button : button event
//
// A button was pressed or released.
//
// time : timestamp with millisecond granularity
// button : button that produced the event
// state : physical state of the button
func (i *VirtualPointer) Button(time uint32, button uint32, state PointerButtonState) {
	if i == nil || !i.Valid() {
		return
	}
	w := wayland.NewMessageWriter(i, 2)
	w.WriteUint(uint32(time))
	w.WriteUint(uint32(button))
	w.WriteUint(uint32(state))
	if err := w.Finish(); err != nil {
		panic(err)
	}
}

// Axis : axis event
//
// Scroll and other axis requests.
//
// time : timestamp with millisecond granularity
// axis : axis type
// value : length of vector in touchpad coordinates
func (i *VirtualPointer) Axis(time uint32, axis PointerAxis, value float64) {
	if i == nil || !i.Valid() {
		return
	}
	w := wayland.NewMessageWriter(i, 3)
	w.WriteUint(uint32(time))
	w.WriteUint(uint32(axis))
	w.WriteFixed(value)
	if err := w.Finish(); err != nil {
		panic(err)
	}
}

// Frame : end of a pointer event sequence
//
// Indicates the set of events that logically belong together.
func (i *VirtualPointer) Frame() {
	if i == nil || !i.Valid() {
		return
	}
	w := wayland.NewMessageWriter(i, 4)
	if err := w.Finish(); err != nil {
		panic(err)
	}
}

// AxisSource : axis source event
//
// Source information for scroll and other axis.
//
// axisSource : source of the axis event
func (i *VirtualPointer) AxisSource(axisSource PointerAxisSource) {
	if i == nil || !i.Valid() {
		return
	}
	w := wayland.NewMessageWriter(i, 5)
	w.WriteUint(uint32(axisSource))
	if err := w.Finish(); err != nil {
		panic(err)
	}
}

// AxisStop : axis stop event
//
// Stop notification for scroll and other axes.
//
// time : timestamp with millisecond granularity
// axis : the axis stopped with this event
func (i *VirtualPointer) AxisStop(time uint32, axis PointerAxis) {
	if i == nil || !i.Valid() {
		return
	}
	w := wayland.NewMessageWriter(i, 6)
	w.WriteUint(uint32(time))
	w.WriteUint(uint32(axis))
	if err := w.Finish(); err != nil {
		panic(err)
	}
}

// AxisDiscrete : axis click event
//
// Discrete step information for scroll and other axes.
//
// This event allows the client to extend data normally sent using the axis
// event with discrete value.
//
// time : timestamp with millisecond granularity
// axis : axis type
// value : length of vector in touchpad coordinates
// discrete : number of steps
func (i *VirtualPointer) AxisDiscrete(time uint32, axis PointerAxis, value float64, discrete int32) {
	if i == nil || !i.Valid() {
		return
	}
	w := wayland.NewMessageWriter(i, 7)
	w.WriteUint(uint32(time))
	w.WriteUint(uint32(axis))
	w.WriteFixed(value)
	w.WriteInt(discrete)
	if err := w.Finish(); err != nil {
		panic(err)
	}
}

// Destroy : destroy the virtual pointer object
func (i *VirtualPointer) Destroy() {
	if i == nil || !i.Valid() {
		return
	}
	w := wayland.NewMessageWriter(i, 8)
	if err := w.Finish(); err != nil {
		panic(err)
	}
}

// VirtualPointerError :
type VirtualPointerError uint32

const (
	// VirtualPointerErrorInvalidAxis : client sent invalid axis enumeration value
	VirtualPointerErrorInvalidAxis VirtualPointerError = 0
	// VirtualPointerErrorInvalidAxisSource : client sent invalid axis source enumeration value
	VirtualPointerErrorInvalidAxisSource VirtualPointerError = 1
)

func (e VirtualPointerError) Name() string {
	switch e {
	case VirtualPointerErrorInvalidAxis:
		return "invalid_axis"
	case VirtualPointerErrorInvalidAxisSource:
		return "invalid_axis_source"
	default:
		return ""
	}
}
func (e VirtualPointerError) String() string {
	name := e.Name()
	if name == "" {
		return fmt.Sprintf("error(%d)", e)
	}
	return fmt.Sprintf("error(%s)", name)
}

// VirtualPointerManager : virtual pointer manager
//
// This object allows clients to create individual virtual pointer objects.
type VirtualPointerManager struct {
	wayland.BaseProxy
	adjacent []wayland.Proxy
}

// NewVirtualPointerManager : virtual pointer manager
//
// This object allows clients to create individual virtual pointer objects.
func NewVirtualPointerManager() *VirtualPointerManager {
	return &VirtualPointerManager{}
}
func (i *VirtualPointerManager) Name() string {
	return "zwlr_virtual_pointer_manager_v1"
}

// CreateVirtualPointer : Create a new virtual pointer
//
// Creates a new virtual pointer. The optional seat is a suggestion to the
// compositor.
func (i *VirtualPointerManager) CreateVirtualPointer(seat *Seat) *VirtualPointer {
	if i == nil || !i.Valid() {
		return nil
	}
	id := NewVirtualPointer()
	i.Conn().Register(id)
	i.adjacent = append(i.adjacent, id)
	w := wayland.NewMessageWriter(i, 0)
	if seat == nil {
		w.WriteUint(0)
	} else {
		w.WriteObject(seat)
	}
	w.WriteObject(id)
	if err := w.Finish(); err != nil {
		panic(err)
	}
	return id
}

// Destroy : destroy the virtual pointer manager
func (i *VirtualPointerManager) Destroy() {
	if i == nil || !i.Valid() {
		return
	}
	w := wayland.NewMessageWriter(i, 1)
	if err := w.Finish(); err != nil {
		panic(err)
	}
}

// CreateVirtualPointerWithOutput : Create a new virtual pointer
//
// Creates a new virtual pointer. The seat and the output arguments are
// optional. If the seat argument is set, the compositor should assign the
// input device to the requested seat. If the output argument is set, the
// compositor should map the input device to the requested output.
func (i *VirtualPointerManager) CreateVirtualPointerWithOutput(seat *Seat, output *Output) *VirtualPointer {
	if i == nil || !i.Valid() {
		return nil
	}
	id := NewVirtualPointer()
	i.Conn().Register(id)
	i.adjacent = append(i.adjacent, id)
	w := wayland.NewMessageWriter(i, 2)
	if seat == nil {
		w.WriteUint(0)
	} else {
		w.WriteObject(seat)
	}
	if output == nil {
		w.WriteUint(0)
	} else {
		w.WriteObject(output)
	}
	w.WriteObject(id)
	if err := w.Finish(); err != nil {
		panic(err)
	}
	return id
}
func GetWlrVirtualPointerUnstableInterface(name string, handler wayland.EventHandler) wayland.Proxy {
	switch name {
	case "zwlr_virtual_pointer_v1":
		return NewVirtualPointer()
	case "zwlr_virtual_pointer_manager_v1":
		return NewVirtualPointerManager()
	default:
		return nil
	}
}
